### PR TITLE
Add gif89a support

### PR DESCRIPTION
**Pull request by nathanoehlman**
Detects GIF89A gifs as `image/gif`.

### CODE REVIEW

**Comment by DamonOehlman** [comment]
So much win :hand:

**Comment by DamonOehlman** [comment]
Sorry, I really didn't do this PR justice with my last comment:

**Comment by DamonOehlman** [comment]
Also, unsurprisingly that PR has earned you collaborator and package publishing permissions.

**Comment by nathanoehlman** [comment]
Awesome :)

Woohoo

**Comment by nathanoehlman** [comment]
Although, I didn't realise just quite how angry an excited Data looks...

**Comment by nathanoehlman** [comment]
Also - had you given any thought as to how to handle multiple different types of signatures?

ie. I didn't put in the gif87a signature which should also resolve to `image/gif` because only one set of checks can be set in the `datablocks.js`.

**Comment by DamonOehlman** [comment]
Hmmm, I though I had already handled this, but apparently not.  My intention was to have a second level of nesting within the datablocks array (something like this):

``` js
module.exports = {
  application: {
    // TODO: support checking for the trailers (4 variations)
    pdf: [ '25 50 44 46' ]
  },

  image: {
    bmp: [ '42 4D' ],
    gif: [
      [ '47 49 46 38 39 61', '00 3B' ],  // gif89a
      ['', ''] // gif87a
    ],
    jpeg: ['FF D8 FF', 'FF D9' ],
    png: [ '89 50 4E 47 0D 0A 1A 0A', '49 45 4E 44 AE 42 60 82' ]
  },

  audio: {
    ogg: [ '4F 67 67 53 00 02 00 00 00 00 00 00 00 00' ]
  }
};
```

Just read through the code though and it definitely doesn't seem to handle any optional nested array magic.  Shouldn't be too hard to add it though...

**Pull request merged**
