### PR TITLE
Support bitmap files

### PR DESCRIPTION
**Pull request by crabmusket**
Pretty please? :grin:

### CODE REVIEW

**Comment by silviapfeiffer** [comment]
@DamonOehlman we'd like this to land, too, please :-)

**Comment by DamonOehlman** [comment]
I see no problem with this - will merge.  @eightyeight you are probably best letting a package maintainer bump versions and stuff as most people do it as part of the package publishing workflow (including git tagging, etc).  I completely agree with your version choice though :)

**Comment by DamonOehlman** [comment]
Also, I don't suppose you folks could source a liberally licensed BMP file too?  The current files are all validated in tests to be working and it would be a shame to break with that fine tradition now...

I'm happy to update the tests (that's quick) but finding a file can take far longer than I'd like...

**Comment by crabmusket** [comment]
@DamonOehlman I've rebased the version bump out and add some tests. Image is CC0 from [here](http://www.pexels.com/photo/nature-butterfly-animal-insect-7021/).

**Comment by DamonOehlman** [comment]
Awesome Dan - I'll merge that now, get the tests running again (some travis-multirunner weirdness going on and then publish a new version).  Should be done shortly :)

**Comment by crabmusket** [comment]
Thanks!

**Comment by DamonOehlman** [comment]
Published `1.2.0`

**Pull request merged**
